import {faInstagram, faTwitter} from '@fortawesome/free-brands-svg-icons'
import {
    faBackward,
    faBookmark,
    faBuilding,
    faCaretDown,
    faCaretUp,
    faChevronDown,
    faCogs,
    faComments,
    faDollarSign,
    faEllipsisH,
    faEllipsisV,
    faExclamationTriangle,
    faFileAudio,
    faFlag,
    faForward,
    faGlobe,
    faHome,
    faList,
    faMapMarkerAlt,
    faMinusCircle,
    faMusic,
    faNewspaper,
    faPause,
    faPlay,
    faPlayCircle,
    faPlus,
    faPlusCircle,
    faReceipt,
    faSave,
    faSearchLocation,
    faSearch,
    faShoppingBag,
    faShoppingCart,
    faSignOutAlt,
    faStar,
    faStepBackward,
    faStepForward,
    faStore,
    faStream,
    faTimesCircle,
    faTrashAlt,
    faUser,
    faUserCog,
    faUsersCog,
    faVolumeMute,
    faVolumeUp,
    faWindowMaximize,
    faWindowMinimize
}                               from '@fortawesome/free-solid-svg-icons'

export const
    bookmark = faBookmark,
    building = faBuilding,
    cogs = faCogs,
    caretDown = faCaretDown,
    chevronDown = faChevronDown,
    comments = faComments,
    caretUp = faCaretUp,
    ellipsis = faEllipsisH,
    ellipsisV = faEllipsisV,
    exclamationTriangle = faExclamationTriangle,
    usd = faDollarSign,
    fileAudio = faFileAudio,
    forward = faForward,
    flag = faFlag,
    globe = faGlobe,
    backward = faBackward,
    home = faHome,
    list = faList,
    mapMarker = faMapMarkerAlt,
    minusCircle = faMinusCircle,
    music = faMusic,
    newsPaper = faNewspaper,
    pause = faPause,
    plus = faPlus,
    plusCircle = faPlusCircle,
    receipt = faReceipt,
    save = faSave,
    searchLocation = faSearchLocation,
    search = faSearch,
    shoppingBag = faShoppingBag,
    shoppingCart = faShoppingCart,
    signOut = faSignOutAlt,
    star = faStar,
    store = faStore,
    stream = faStream,
    stepBackward = faStepBackward,
    stepForward = faStepForward,
    play = faPlay,
    playCircle = faPlayCircle,
    timesCircle = faTimesCircle,
    trashAlt = faTrashAlt,
    twitter = faTwitter,
    instagram = faInstagram,
    user = faUser,
    users = faUsersCog,
    userCog = faUserCog,
    windowMinimize = faWindowMinimize,
    windowMaximize = faWindowMaximize,
    volumeMute = faVolumeMute,
    volumeUp = faVolumeUp
