import {faInstagram, faTwitter, faGithub} from '@fortawesome/free-brands-svg-icons'
import {
    faBackward,
    faBookmark,
    faBuilding,
    faCamera,
    faCaretDown,
    faCaretUp,
    faChevronDown,
    faCogs,
    faComments,
    faDollarSign,
    faDoorOpen,
    faEllipsisH,
    faEllipsisV,
    faExclamationTriangle,
    faFileAudio,
    faFlag,
    faForward,
    faGlobe,
    faHandHoldingHeart,
    faHome,
    faList,
    faMapMarkerAlt,
    faMinusCircle,
    faMusic,
    faNewspaper,
    faPause,
    faPlay,
    faPlayCircle,
    faPlus,
    faPlusCircle,
    faReceipt,
    faSave,
    faSearch,
    faSearchLocation,
    faShoppingBag,
    faShoppingCart,
    faSignOutAlt,
    faSpa,
    faStar,
    faStepBackward,
    faStepForward,
    faStore,
    faStream,
    faTags, faTimes,
    faTimesCircle,
    faTrashAlt,
    faUser,
    faUserCog,
    faUsersCog,
    faVolumeMute,
    faVolumeUp,
    faWindowMaximize,
    faWindowMinimize
} from '@fortawesome/free-solid-svg-icons'

import {
    faMapMarkerAlt as faMapMarkerAltSolid,
    faTimesCircle as faTimesCircleSolid,
    faInfoCircle,
    faChevronCircleDown,
    faChevronCircleUp
} from '@fortawesome/pro-solid-svg-icons'

export const
    bookmark = faBookmark,
    building = faBuilding,
    camera = faCamera,
    cogs = faCogs,
    caretDown = faCaretDown,
    chevronDown = faChevronDown,
    chevronCircleDown = faChevronCircleDown,
    chevronCircleUp = faChevronCircleUp,
    comments = faComments,
    caretUp = faCaretUp,
    doorOpen = faDoorOpen,
    ellipsis = faEllipsisH,
    ellipsisV = faEllipsisV,
    exclamationTriangle = faExclamationTriangle,
    usd = faDollarSign,
    fileAudio = faFileAudio,
    forward = faForward,
    flag = faFlag,
    github = faGithub,
    globe = faGlobe,
    backward = faBackward,
    handHoldingHeart = faHandHoldingHeart,
    home = faHome,
    infoCircle = faInfoCircle,
    list = faList,
    mapMarker = faMapMarkerAlt,
    mapMarkerSolid = faMapMarkerAltSolid,
    minusCircle = faMinusCircle,
    music = faMusic,
    newsPaper = faNewspaper,
    pause = faPause,
    plus = faPlus,
    plusCircle = faPlusCircle,
    receipt = faReceipt,
    save = faSave,
    searchLocation = faSearchLocation,
    search = faSearch,
    shoppingBag = faShoppingBag,
    shoppingCart = faShoppingCart,
    signOut = faSignOutAlt,
    spa = faSpa,
    star = faStar,
    store = faStore,
    stream = faStream,
    stepBackward = faStepBackward,
    stepForward = faStepForward,
    play = faPlay,
    playCircle = faPlayCircle,
    tags = faTags,
    times = faTimes,
    timesCircle = faTimesCircle,
    timesCircleSolid = faTimesCircleSolid,
    trashAlt = faTrashAlt,
    twitter = faTwitter,
    instagram = faInstagram,
    user = faUser,
    users = faUsersCog,
    userCog = faUserCog,
    windowMinimize = faWindowMinimize,
    windowMaximize = faWindowMaximize,
    volumeMute = faVolumeMute,
    volumeUp = faVolumeUp
