export const API = process.env.REACT_APP_API_URL
export const CDN = process.env.REACT_APP_CDN_URL
export const algoliaAppId = process.env.REACT_APP_ALGOLIA_APP_ID
export const algoliaSearchApiKey = process.env.REACT_APP_ALGOLIA_ADMIN_API_KEY
export const alogiaAdminKey = process.env.REACT_APP_ALGOLIA_ADMIN_API_KEY
export const googlePlacesApiKey = process.env.REACT_APP_PLACES_API_KEY
export const shippoApiKey = process.env.REACT_APP_SHIPPO_API_KEY
export const siteDisplayName = 'Hypha Beta'
export const postUploadPath = 'post-profile/'
export const shopUploadPath = 'shop/'